name: Ecommerce - User Service Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests
        env:
          FLASK_APP: 'src/app'
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python -m unittest discover tests

      - name: Test Results
        if: failure()
        run: echo "One or more tests failed. See the log for details."
